// ============================================================
//  products.js  —  Fix-It Forward Shop · Product Data
//  65 products · 8 categories · ratings · sizes
// ============================================================

const products = [

  // ── ELECTRONICS (1–10) ──────────────────────────────────────
  { id:1,  name:"Wireless Noise-Cancelling Headphones", description:"Premium sound with 30hr battery life and active noise cancellation. Foldable design with memory foam ear cushions. Compatible with all Bluetooth 5.0 devices.", price:89.99,  comparePrice:129.99, stock:12, category:"Electronics", rating:4.5, reviews:128, sizes:[], image:"https://i.ibb.co/czSb0gF/c8a4b246382b1db8716e7557bdd97ea2-hi.jpg?w=600&q=80" },
  { id:2,  name:"Mechanical Keyboard TKL",              description:"Tenkeyless layout with tactile brown switches and per-key RGB backlight. N-key rollover, PBT keycaps, detachable USB-C cable.",                                  price:109.99, comparePrice:149.99, stock:5,  category:"Electronics", rating:4.7, reviews:89,  sizes:[], image:"https://i.ibb.co/qFRP8RP7/kb500-01.webp?w=600&q=80" },
  { id:3,  name:"4K Webcam Ultra HD",                   description:"Crystal-clear 4K video with auto-focus, built-in ring light and noise-cancelling dual microphone. Plug and play, no drivers needed.",                             price:74.99,  comparePrice:99.99,  stock:9,  category:"Electronics", rating:4.3, reviews:54,  sizes:[], image:"https://i.ibb.co/xKNFWnMC/61-P2-Wb-Rohx-L.jpg?w=600&q=80" },
  { id:4,  name:"Portable Bluetooth Speaker",           description:"360° surround sound, waterproof IPX7 rating, 20hr playtime on a single charge. Built-in speakerphone and USB-C fast charging.",                                  price:59.99,  comparePrice:79.99,  stock:14, category:"Electronics", rating:4.6, reviews:203, sizes:[], image:"https://i.ibb.co/TB8v9c2v/images-q-tbn-ANd9GcR9c.jpg?w=600&q=80" },
  { id:5,  name:"Smart LED Desk Lamp",                  description:"Touch-dimming with 5 brightness levels, adjustable colour temperature from warm to cool white, and a built-in USB-C charging port.",                              price:44.99,  comparePrice:null,   stock:20, category:"Electronics", rating:4.2, reviews:67,  sizes:[], image:"https://i.ibb.co/Rk8RpdLT/67572327.jpg?w=600&q=80" },
  { id:6,  name:"Wireless Charging Pad",                description:"15W fast-charge Qi pad compatible with all wireless-charging devices. Sleek matte finish with LED indicator. Anti-slip base.",                                    price:29.99,  comparePrice:39.99,  stock:22, category:"Electronics", rating:4.1, reviews:41,  sizes:[], image:"https://i.ibb.co/nFjw2LZ/61-FLVn-Q3-Cd-L.jpg?w=600&q=80" },
  { id:7,  name:"USB-C Hub 7-in-1",                     description:"HDMI 4K@60Hz, 3× USB-A 3.0, SD/microSD card reader, and PD 100W pass-through in one ultra-slim aluminium hub.",                                                  price:49.99,  comparePrice:64.99,  stock:17, category:"Electronics", rating:4.4, reviews:112, sizes:[], image:"https://i.ibb.co/FkbQGwPm/61-OPk-Ky-EM8-L.jpg?w=600&q=80" },
  { id:8,  name:"Smart Watch Series X",                 description:"24/7 health tracking with SpO2, ECG, GPS, 5-day battery life and 100+ workout modes. Water resistant to 50m. Customisable watch faces.",                         price:199.99, comparePrice:249.99, stock:7,  category:"Electronics", rating:4.8, reviews:315, sizes:[], image:"https://i.ibb.co/1Gt1h7wf/61-ZOMrc-Re-JL-AC-UF1000-1000-QL80.jpg?w=600&q=80" },
  { id:9,  name:"Noise-Isolating Earbuds",              description:"True wireless earbuds with 8hr playtime (+24hr with case), transparency mode, IPX4 sweat resistance, and three ear-tip sizes included.",                          price:69.99,  comparePrice:null,   stock:11, category:"Electronics", rating:4.3, reviews:88,  sizes:[], image:"https://i.ibb.co/398TVLb4/51z1-NKe-W1a-L-AC-UF1000-1000-QL80.jpg?w=600&q=80" },
  { id:10, name:"Mini Projector HD",                    description:"1080p native resolution, 200 ANSI lumens, built-in stereo speaker, HDMI & USB input. Projects up to 120\" screen. Keystone correction.",                         price:149.99, comparePrice:199.99, stock:4,  category:"Electronics", rating:4.0, reviews:29,  sizes:[], image:"https://i.ibb.co/S41m2gbT/51-TF2-Zxw-FEL.jpg?w=600&q=80" },

  // ── KITCHEN (11–20) ─────────────────────────────────────────
  { id:11, name:"Ceramic Pour-Over Coffee Set",   description:"Handcrafted ceramic dripper with matching 350ml mug. The ridged interior ensures even extraction for a perfectly balanced cup every time.",              price:54.00,  comparePrice:70.00,  stock:8,  category:"Kitchen", rating:4.6, reviews:77,  sizes:[], image:"https://i.ibb.co/QF0nmcSD/71p-SRa-N2vp-L-AC-UF1000-1000-QL80.jpg?w=600&q=80" },
  { id:12, name:"Cast Iron Skillet 10\"",          description:"Pre-seasoned cast iron skillet. Even heat distribution, oven-safe to 260°C. Suitable for all hob types including induction. Includes silicone handle grip.", price:39.99,  comparePrice:54.99,  stock:15, category:"Kitchen", rating:4.7, reviews:142, sizes:[], image:"https://i.ibb.co/kRKyYcp/how-to-make-your-favorite-cast-iron-skillet-last-forever-1022-2000-5edb8809448b46e2ac64ad7305aafb3a.jpg?w=600&q=80" },
  { id:13, name:"Bamboo Cutting Board Set",        description:"Set of 3 organic bamboo boards (S/M/L) with juice grooves and non-slip rubber feet. Dishwasher safe and naturally antimicrobial.",                          price:32.00,  comparePrice:null,   stock:19, category:"Kitchen", rating:4.4, reviews:56,  sizes:[], image:"https://i.ibb.co/hJJ8kFbc/165687845-165687845-HMBX09102023-N-01-2100.jpg?w=600&q=80" },
  { id:14, name:"Electric Milk Frother",           description:"Four frothing modes — hot foam, cold foam, hot milk, warm milk. Heats and froths in under 2 minutes. 500ml capacity, non-stick interior.",               price:24.99,  comparePrice:34.99,  stock:23, category:"Kitchen", rating:4.3, reviews:91,  sizes:[], image:"https://i.ibb.co/wZbWHp8c/41sk-A-hn-Od-L.jpg?w=600&q=80" },
  { id:15, name:"Spice Rack Organiser",            description:"Rotating 3-tier bamboo rack holds 18 standard spice jars. Lazy-Susan base spins 360°. Saves counter space and keeps spices organised.",                     price:27.99,  comparePrice:null,   stock:12, category:"Kitchen", rating:4.1, reviews:34,  sizes:[], image:"https://i.ibb.co/vxv4CjfZ/71-QGflv-Up-LL-SL1500.jpg" },
  { id:16, name:"Silicone Utensil Set (6pc)",      description:"Heat-resistant to 250°C. Non-scratch, dishwasher safe, BPA-free. Includes spatula, ladle, spoon, slotted spoon, whisk, and pasta server.",                price:21.99,  comparePrice:29.99,  stock:30, category:"Kitchen", rating:4.2, reviews:48,  sizes:[], image:"https://i.ibb.co/dJXCVzxy/71-Rrk284-WNL-AC-UF1000-1000-QL80.jpg?w=600&q=80"},
  { id:17, name:"Glass Meal Prep Containers",      description:"Set of 5 airtight borosilicate glass containers (250ml–1.2L). Microwave, oven, freezer and dishwasher safe. Snap-lock bamboo lids.",                       price:36.99,  comparePrice:48.00,  stock:16, category:"Kitchen", rating:4.5, reviews:63,  sizes:[], image:"https://i.ibb.co/GfyKqtPF/615w-S7-On6-L-AC-UF1000-1000-QL80.jpg?w=600&q=80" },
  { id:18, name:"Handheld Immersion Blender",      description:"500W motor, stainless steel blade guard, 5-speed dial and turbo mode. Easy-clean detachable shaft. Includes whisk and chopper attachments.",               price:44.99,  comparePrice:59.99,  stock:10, category:"Kitchen", rating:4.4, reviews:79,  sizes:[], image:"https://i.ibb.co/4ZHrz3FZ/81-ARw-Ed-R0z-L-AC-UF350-350-QL80.jpg?w=600&q=80" },
  { id:19, name:"Marble Rolling Pin",              description:"Solid marble with acacia wood handles. Stays naturally cool — ideal for pastry, cookies, and bread dough. 45cm total length.",                              price:29.99,  comparePrice:null,   stock:9,  category:"Kitchen", rating:4.0, reviews:22,  sizes:[], image:"https://i.ibb.co/Mxt4vSkd/611-KWy-TL-L.jpg?w=600&q=80" },
  { id:20, name:"Digital Kitchen Scale",           description:"Accurate to 1g, 5kg capacity, tare function, backlit display, slim stainless steel platform. Runs on 2× AAA batteries (included).",                       price:18.99,  comparePrice:24.99,  stock:28, category:"Kitchen", rating:4.3, reviews:107, sizes:[], image:"https://i.ibb.co/NgF8FJhg/61-Vt5-Egqf4-L-AC-UF1000-1000-QL80.jpg?w=600&q=80" },

  // ── MAKE UP (21–30) ─────────────────────────────────────────
  { id:21, name:"Velvet Matte Lipstick",       description:"Long-wearing formula in 12 rich shades from nude to deep berry. Hydrating vitamin E complex keeps lips comfortable all day. Transfer-proof finish.",   price:18.99, comparePrice:24.99, stock:35, category:"Make Up", rating:4.5, reviews:234, sizes:[], image:"https://i.ibb.co/G4kDV32Z/61-G10-KYu-IBL-AC-UF1000-1000-QL80.jpg?w=600&q=80" },
  { id:22, name:"Full-Coverage Foundation",    description:"Buildable coverage from light to full, SPF 30 protection, 24-hour wear formula. Available in 40 shades. Dermatologist tested, non-comedogenic.",           price:32.00, comparePrice:null,   stock:20, category:"Make Up", rating:4.4, reviews:189, sizes:[], image:"https://i.ibb.co/1JRbWgXR/1.jpg?w=600&q=80" },
  { id:23, name:"Eyeshadow Palette — Neutrals",description:"18 blendable shades from soft mattes to bold glitters. Ultra-pigmented formula with 72-hour wear. Includes a dual-ended brush.",                            price:44.99, comparePrice:59.99,  stock:14, category:"Make Up", rating:4.7, reviews:301, sizes:[], image:"https://i.ibb.co/j9PxcyhB/61-Kjdk50-X0-L.jpg?w=600&q=80" },
  { id:24, name:"Precision Brow Pencil",       description:"Micro-tip retractable pencil with spoolie brush. Fills, defines and sets brows. Waterproof, sweat-proof, and humidity-resistant formula.",                  price:14.99, comparePrice:null,   stock:40, category:"Make Up", rating:4.2, reviews:145, sizes:[], image:"https://i.ibb.co/bM8tLMf2/custom-logo-cosmetics-no-brand-matt-pigmented-high-quality-make-up-private-label-aut-eyebrow-pencil1.jpg?w=600&q=80" },
  { id:25, name:"Volumising Mascara",          description:"Curved hourglass brush coats every lash from root to tip. Clump-free formula adds up to 5× volume. Ophthalmologist tested, contact-lens safe.",            price:16.99, comparePrice:21.99,  stock:28, category:"Make Up", rating:4.3, reviews:178, sizes:[], image:"https://i.ibb.co/CKYQn9N8/YN-LUX-WTRPRF-MASC-Black-WSWP-75191-V1-WEB-2500px.webp?w=600&q=80" },
  { id:26, name:"Liquid Highlighter",          description:"Buildable luminous glow. Wear alone, mix with foundation, or layer over makeup. Rose gold, champagne, and icy pink shades available.",                      price:22.99, comparePrice:null,   stock:18, category:"Make Up", rating:4.4, reviews:92,  sizes:[], image:"https://i.ibb.co/YSpnzHB/71-u-RH5-Kx2-L-AC-UF1000-1000-QL80.jpg?w=600&q=80" },
  { id:27, name:"Makeup Brush Set (12pc)",     description:"Professional-grade synthetic vegan bristles. Includes face, contour, eye and blending brushes. Rose gold ferrules, weighted handles.",                      price:38.00, comparePrice:52.00,  stock:11, category:"Make Up", rating:4.6, reviews:267, sizes:[], image:"https://i.ibb.co/hxS8NFck/images-q-tbn-ANd9-Gc-Q3gi9gp-Jz-E6-Dw-Nf-h-Qm7b-I3k-Vf-Wy50vx-ESsg-s.jpg" },
  { id:28, name:"Setting Spray — Dewy Finish", description:"100ml fine-mist spray locks makeup for 16 hours and adds a fresh skin-like glow. Infused with hyaluronic acid and green tea extract.",                      price:19.99, comparePrice:26.99,  stock:22, category:"Make Up", rating:4.1, reviews:83,  sizes:[], image:"https://i.ibb.co/Xhj402x/images-q-tbn-ANd9-Gc-TKQl2ewgoxt-Toecy-Lmdus-e4-I7-Bw-ZEFLa-Wg-s.jpg?w=600&q=80" },
  { id:29, name:"Contour & Blush Duo",         description:"Pressed powder palette with a cool-toned contour and warm peachy blush shade. Silky formula blends seamlessly, buildable and long-lasting.",               price:27.99, comparePrice:null,   stock:16, category:"Make Up", rating:4.3, reviews:119, sizes:[], image:"https://i.ibb.co/XfKg8hfj/81-YX-jj-VG9-L-AC-UF350-350-QL80.jpg?w=600&q=80" },
  { id:30, name:"Lip Gloss — Glass Effect",    description:"Non-sticky plumping gloss in 8 shades. Hyaluronic acid gives a pillowy pout. High-shine mirror finish that lasts up to 6 hours.",                          price:13.99, comparePrice:17.99,  stock:33, category:"Make Up", rating:4.2, reviews:156, sizes:[], image:"https://i.ibb.co/LX3STXdJ/Lip-oil.jpg?w=600&q=80" },

  // ── WOMEN'S (31–35) ─────────────────────────────────────────
  { id:31, name:"Satin Slip Dress",            description:"Bias-cut charmeuse satin, adjustable spaghetti straps, side slit, V-neckline. Lined. Wear alone or layer over a turtleneck. Available in 6 colours.",      price:74.99,  comparePrice:99.99,  stock:7,  category:"Women's", rating:4.7, reviews:189, sizes:["XS","S","M","L"],            image:"https://i.ibb.co/1fhNgzV4/7cd5e860bb07b56fc548f56a0e02a37c.jpg?w=600&q=80" },
  { id:32, name:"High-Rise Straight Jeans",    description:"Stretch denim in vintage wash. High-rise waist, straight leg, 5-pocket style. 2% elastane for all-day comfort. Sizes 24–34.",                              price:69.99,  comparePrice:89.99,  stock:14, category:"Women's", rating:4.5, reviews:211, sizes:["XS","S","M","L","XL"],      image:"https://i.ibb.co/3YdHL503/217498039-000-pk.jpg?w=600&q=80" },
  { id:33, name:"Oversized Knit Sweater",      description:"Cosy ribbed knit in oat, sage, and charcoal. Drop-shoulder cut for a relaxed fit. 80% merino wool, 20% nylon. Hand wash cold.",                            price:62.00,  comparePrice:null,   stock:10, category:"Women's", rating:4.6, reviews:143, sizes:["S","M","L","XL"],           image:"https://i.ibb.co/9m6rZ7c9/hzz33376-taupe-xl-1.jpg?w=600&q=80" },
  { id:34, name:"Linen Wide-Leg Trousers",     description:"Breathable pure linen with an elasticated drawstring waist and two side pockets. Relaxed summer cut. Available in sand, white, and navy.",                  price:58.00,  comparePrice:72.00,  stock:9,  category:"Women's", rating:4.3, reviews:76,  sizes:["XS","S","M","L","XL"],      image:"https://i.ibb.co/RTdW1hCd/76e301811249ebd8071b85a4369f1c1f02cdc59d-CNM6658-1-natural-premium-linen-side-tie-detail-wide-leg-tr.jpg?w=600&q=80" },
  { id:35, name:"Ribbed Bralette",             description:"Soft stretch rib fabric, longline cut, cross-back straps, removable padding. Comfortable enough for all-day wear, stylish enough to show off.",             price:22.99,  comparePrice:29.99,  stock:20, category:"Women's", rating:4.1, reviews:92,  sizes:["XS","S","M","L"],            image:"https://i.ibb.co/jkQXfCPN/images-q-tbn-ANd9-Gc-Sc-J4-Fa-URLGGmd-YCWd-WLIMv-BZfi-Nzn-Wiasj-Dg-s.jpg?w=600&q=80" },

  // ── MEN'S (36–40) ───────────────────────────────────────────
  { id:36, name:"Classic White Oxford Shirt",  description:"100% Egyptian cotton, slim fit, mother-of-pearl buttons and a split hem. Machine washable. Available in sizes XS to XXL.",                                  price:54.99,  comparePrice:74.99,  stock:18, category:"Men's",   rating:4.4, reviews:98,  sizes:["XS","S","M","L","XL","XXL"], image:"https://i.ibb.co/0WpTJVM/s7-1320644-alternate10-plp-Desk-RF.webp?w=600&q=80" },
  { id:37, name:"Structured Blazer",           description:"Single-breasted notch lapel blazer, fully lined with an interior pocket. Slightly padded shoulders for a polished silhouette.",                              price:119.99, comparePrice:159.99, stock:6,  category:"Men's",   rating:4.5, reviews:67,  sizes:["XS","S","M","L","XL","XXL"], image:"https://i.ibb.co/RTgv6yrg/R198175-4-ab33977c-9bdb-4524-87e5-c2faab28236a-1800x1800.jpg?w=600&q=80" },
  { id:38, name:"Graphic Tee — Vintage Print", description:"Washed 100% organic cotton in a relaxed unisex fit. Screen-printed vintage graphic. Pre-shrunk. Available in white, black, and light grey.",                price:28.99,  comparePrice:null,   stock:25, category:"Men's",   rating:4.2, reviews:134, sizes:["XS","S","M","L","XL","XXL"], image:"https://i.ibb.co/BVFm8LPY/SSS2-NW60565041-001-198058847538-1.jpg?w=600&q=80" },
  { id:39, name:"Trench Coat Classic",         description:"Waterproof cotton-blend gabardine, detachable belt, double-breasted buttons, storm flap. Fully lined. A timeless investment piece.",                        price:189.99, comparePrice:240.00, stock:5,  category:"Men's",   rating:4.8, reviews:88,  sizes:["XS","S","M","L","XL"],      image:"https://i.ibb.co/C57T6R9G/s7-1450355-alternate10-rl-4x5-pdp.webp?w=600&q=80" },
  { id:40, name:"Fleece Zip-Up Hoodie",        description:"Heavyweight 380gsm fleece, full YKK zip, kangaroo pockets, adjustable hood. Available in 6 colours. Brushed interior for extra warmth.",                   price:64.99,  comparePrice:84.99,  stock:13, category:"Men's",   rating:4.4, reviews:167, sizes:["S","M","L","XL","XXL"],     image:"https://i.ibb.co/8nPzXr9f/71vd-Eze-AKg-L-AC-SL1500.jpg?w=600&q=80" },

  // ── KIDS (41–45) ────────────────────────────────────────────
  { id:41, name:"Dinosaur Print Hoodie",       description:"Super-soft 100% cotton fleece with an all-over dinosaur print. Kangaroo pocket and adjustable hood. Machine washable. Ages 3–12.",                          price:24.99,  comparePrice:34.99,  stock:22, category:"Kids",    rating:4.8, reviews:312, sizes:["3-4Y","5-6Y","7-8Y","9-10Y","11-12Y"], image:"https://i.ibb.co/3m40LW37/images-q-tbn-ANd9-Gc-Tt-B47m-Iz-MZ7-v-Vp-XT6zuq0kj-OE2-Gis-TGlkpg-s.jpg?w=600&q=80" },
  { id:42, name:"Rainbow Tutu Dress",          description:"Lightweight chiffon layers in rainbow colours with a comfortable elasticated waist. Perfect for parties, dancing, and everyday play. Ages 2–8.",             price:19.99,  comparePrice:26.99,  stock:18, category:"Kids",    rating:4.7, reviews:204, sizes:["2-3Y","3-4Y","5-6Y","7-8Y"],           image:"https://i.ibb.co/yFLDZbgM/660bbea25b614943502e37c0-o-39-cocolour-rainbow-candy-tutu-dress.jpg?w=600&q=80" },
  { id:43, name:"Kids Denim Dungarees",        description:"Classic bib-and-brace style in stretch denim. Adjustable straps, side pockets, and a back patch pocket. Durable and easy to move in. Ages 2–10.",           price:29.99,  comparePrice:null,   stock:15, category:"Kids",    rating:4.5, reviews:89,  sizes:["2-3Y","3-4Y","5-6Y","7-8Y","9-10Y"],   image:"https://i.ibb.co/trSSwCh/images-q-tbn-ANd9-Gc-Rko6-NQfg-W8-Sl-AN0-Him-K-t-Iwyp9kc-Udt-SF-Yw-s.jpg?w=600&q=80" },
  { id:44, name:"Superhero Cape Set",          description:"Mix-and-match cape and mask set in 4 colours. Satin finish, velcro fastening, one size fits most. Great for dress-up and imaginative play. Ages 3–8.",       price:14.99,  comparePrice:19.99,  stock:30, category:"Kids",    rating:4.9, reviews:445, sizes:["One Size"],                            image:"https://i.ibb.co/YFg1jkbL/gw-sprmclk-jade-superman-superhero-cape-with-mask-halloween-costume-1571404874.jpg?w=600&q=80" },
  { id:45, name:"Cosy Stripe Pyjama Set",      description:"100% brushed cotton pyjama set with a striped top and matching bottoms. Elasticated waist, ribbed cuffs. Wonderfully soft for bedtime. Ages 2–12.",          price:22.99,  comparePrice:29.99,  stock:24, category:"Kids",    rating:4.6, reviews:178, sizes:["2-3Y","3-4Y","5-6Y","7-8Y","9-10Y","11-12Y"], image:"https://i.ibb.co/XMQ5p1D/51-WB-6-K6-Gb-L-AC-SY1000.jpg?w=600&q=80" },

  // ── ACCESSORIES (46–55) ─────────────────────────────────────
  { id:46, name:"Minimalist Leather Wallet",  description:"Full-grain vegetable-tanned leather, RFID-blocking lining, 8-card capacity with a central cash slip. Available in tan, black, and navy.",               price:34.99, comparePrice:null,   stock:25, category:"Accessories", rating:4.5, reviews:203, sizes:[], image:"https://i.ibb.co/b5Rb0Tdc/images-q-tbn-ANd9-Gc-Qy-Ho-PB3s-W1oxitv-Iq-Ew-MJ7-T6c-Nq-P7y-Wsu-Ah-Q-s.jpg?w=600&q=80" },
  { id:47, name:"Tortoiseshell Sunglasses",   description:"UV400 polarised lenses, lightweight Italian acetate frame, spring-hinge temples. Comes with microfibre pouch and hard case.",                            price:49.99, comparePrice:65.00,  stock:17, category:"Accessories", rating:4.3, reviews:89,  sizes:[], image:"https://i.ibb.co/Mx3L9pXs/41kf-Ol8-An0-L-AC.jpg?w=600&q=80" },
  { id:48, name:"Canvas Tote Bag",            description:"Heavy-duty 12oz natural canvas, inner zip pocket, two interior slip pockets, and veg-tan leather handles. Holds A4 documents easily.",                   price:26.99, comparePrice:null,   stock:30, category:"Accessories", rating:4.2, reviews:56,  sizes:[], image:"https://i.ibb.co/twtjgPSL/81gt-t-L77-NL.jpg?w=600&q=80" },
  { id:49, name:"Beaded Bracelet Set",        description:"Set of 5 handmade natural stone bead bracelets — lapis, tiger eye, obsidian, rose quartz, and jade. Elastic cord fits most wrist sizes.",               price:19.99, comparePrice:27.99,  stock:40, category:"Accessories", rating:4.1, reviews:178, sizes:[], image:"https://i.ibb.co/Zp81vsRH/images-q-tbn-ANd9-Gc-TXc-Ld-JRt-QEVZp5br4-Iz-r-RKojpom-CAAFEd-Ww-s.jpg?w=600&q=80" },
  { id:50, name:"Silk Neck Scarf",            description:"100% pure silk twill, 70×70cm, hand-rolled edges, and a vibrant geometric print. Wear as a neck scarf, headband, or bag accent.",                       price:38.00, comparePrice:50.00,  stock:12, category:"Accessories", rating:4.4, reviews:44,  sizes:[], image:"https://i.ibb.co/dsHpVS7g/R04522790-FIG-M-PLP-ALL.jpg?w=600&q=80" },
  { id:51, name:"Leather Card Holder",        description:"Full-grain leather, 6-card capacity with a quick-access outer slot, 4mm slim profile. Fits in any pocket without bulge.",                               price:22.99, comparePrice:null,   stock:22, category:"Accessories", rating:4.3, reviews:67,  sizes:[], image:"https://i.ibb.co/7xXnz5t1/81h7-QAujm-WL-AC-UY1000.jpg?w=600&q=80" },
  { id:52, name:"Gold Hoop Earrings",         description:"14k gold-filled 30mm hoops with a hinged closure for easy wearing. Lightweight for all-day wear. Hypoallergenic and tarnish-resistant.",                price:29.99, comparePrice:39.99,  stock:18, category:"Accessories", rating:4.6, reviews:312, sizes:[], image:"https://i.ibb.co/xqDvNqKb/Embella-27-May-2025-0056.jpg" },
  { id:53, name:"Woven Straw Hat",            description:"Natural seagrass weave with an adjustable inner grosgrain ribbon band and a generous 6cm brim. UPF 50+ sun protection.",                                price:31.99, comparePrice:null,   stock:9,  category:"Accessories", rating:4.0, reviews:33,  sizes:[], image:"https://i.ibb.co/R4sPZ2Hy/images-q-tbn-ANd9-Gc-Sd6-BTjjzzz-K9z-Pbe-TCu0l5i4-Hc-Ud-Ni-DXr-GBQ-s.jpg?w=600&q=80" },
  { id:54, name:"Leather Belt — Tan",         description:"Full-grain tan leather, 35mm width, solid brass single-pin buckle. Available in waist sizes 28\"–42\". Will patina beautifully with wear.",              price:44.99, comparePrice:58.00,  stock:14, category:"Accessories", rating:4.2, reviews:51,  sizes:[], image:"https://i.ibb.co/NQhyyfS/TB-169572-200-SLFRO-pdp-2642x3000.jpg?w=600&q=80" },
  { id:55, name:"Mini Crossbody Bag",         description:"Vegan pebbled leather, adjustable 120cm strap, magnetic snap closure, 1 zip pocket, 2 card slots. Fits phone, keys, and cards.",                       price:56.99, comparePrice:74.99,  stock:8,  category:"Accessories", rating:4.5, reviews:144, sizes:[], image:"https://i.ibb.co/wFp6H6vF/35e329353d6d5f9a39f7c963b5e422c2-001.jpg?w=600&q=80" },

  // ── FITNESS (56–65) ─────────────────────────────────────────
  { id:56, name:"Yoga Mat Pro",               description:"6mm thick closed-cell TPE foam, double-sided non-slip texture with alignment guide lines. Includes carry strap. Eco-friendly, latex-free.",                price:42.00,  comparePrice:null,   stock:18, category:"Fitness", rating:4.6, reviews:189, sizes:[], image:"https://i.ibb.co/W4t2smTT/e3b64c95-963b-4f93-923b-701c8c412524.jpg?w=600&q=80" },
  { id:57, name:"Stainless Steel Water Bottle",description:"Double-walled 500ml vacuum insulation. Keeps drinks cold 24hr, hot 12hr. Leak-proof lid, wide mouth, powder-coated finish. BPA-free.",                  price:27.99,  comparePrice:35.00,  stock:30, category:"Fitness", rating:4.5, reviews:267, sizes:[], image:"https://i.ibb.co/Gv7VJ6jY/71w-Fy-Zlg58-L.jpg?w=600&q=80" },
  { id:58, name:"Resistance Band Set (5pc)",   description:"5 resistance levels: 10, 20, 30, 40, 50lb. Anti-snap latex core with soft fabric cover. Includes carry bag and exercise guide.",                        price:24.99,  comparePrice:34.99,  stock:22, category:"Fitness", rating:4.4, reviews:134, sizes:[], image:"https://i.ibb.co/fzs3bvpz/71c5-Q-e-2-CL-AC-UF1000-1000-QL80.jpg?w=600&q=80" },
  { id:59, name:"Adjustable Dumbbell 20kg",    description:"Quick-select dial adjusts weight in 2kg increments from 2kg to 20kg. Replaces 10 individual dumbbells. Compact tray storage included.",                 price:129.99, comparePrice:169.99, stock:6,  category:"Fitness", rating:4.7, reviews:78,  sizes:[], image:"https://i.ibb.co/d4TFDYXy/71-YIGXyie-VL.jpg?w=600&q=80" },
  { id:60, name:"Jump Rope — Speed Cable",     description:"Sealed ball-bearing handles, adjustable aircraft-grade steel cable, 360° rotation for fatigue-free skipping. Ideal for HIIT and boxing training.",      price:16.99,  comparePrice:null,   stock:35, category:"Fitness", rating:4.3, reviews:98,  sizes:[], image:"https://i.ibb.co/FL1ZBC35/71-A3nb-Qzc-L.jpg?w=600&q=80" },
  { id:61, name:"Foam Roller Deep Tissue",     description:"High-density EVA foam, 33cm length, multi-zone textured surface for targeted myofascial release. Hollow core holds full body weight.",                   price:22.99,  comparePrice:29.99,  stock:20, category:"Fitness", rating:4.2, reviews:112, sizes:[], image:"https://i.ibb.co/S74Y9szk/61-YFRt-G4xt-L-AC-UF1000-1000-QL80.jpg?w=600&q=80" },
  { id:62, name:"Gym Duffle Bag",              description:"45L capacity with separate wet/dry compartment, vented shoe pocket, and padded laptop sleeve. Padded shoulder strap and top grab handle.",               price:54.99,  comparePrice:69.99,  stock:13, category:"Fitness", rating:4.4, reviews:88,  sizes:[], image:"https://i.ibb.co/r20tcBV3/61-Ffz-M5o4-DL.jpg?w=600&q=80" },
  { id:63, name:"Ab Wheel Roller",             description:"Extra-wide dual wheel for stability, ergonomic foam-grip handles, non-slip mat included. Builds core strength, back, and shoulder muscles.",              price:19.99,  comparePrice:null,   stock:17, category:"Fitness", rating:4.1, reviews:56,  sizes:[], image:"https://i.ibb.co/chhCDc3J/71t-Udy-Apm-L.jpg?w=600&q=80" },
  { id:64, name:"Compression Leggings",        description:"4-way stretch recycled nylon, high-rise waistband, moisture-wicking, squat-proof lining with a hidden waistband pocket. Available in 6 colours.",        price:44.99,  comparePrice:58.00,  stock:16, category:"Fitness", rating:4.6, reviews:223, sizes:["XS","S","M","L","XL"],      image:"https://i.ibb.co/V0h8QJNG/129809-011-size-S-1-461x586.jpg?w=600&q=80" },
  { id:65, name:"Pull-Up Bar Doorframe",       description:"No-screw doorframe design, fits door widths 62–92cm, rated to 150kg. Padded grip, multiple hand positions. Folds flat for storage.",                    price:34.99,  comparePrice:44.99,  stock:10, category:"Fitness", rating:4.3, reviews:67,  sizes:[], image:"https://i.ibb.co/hJ1Zb4C4/51w-EUv-Qxt-FL.jpg?w=600&q=80" },
];
